# Generated by Django 4.2.1 on 2023-06-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='percentage',
            field=models.CharField(max_length=10),
        ),
    ]
