# Generated by Django 4.2.1 on 2023-06-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0002_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='user_name',
        ),
        migrations.AddField(
            model_name='registeruser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='registeruser',
            name='username',
            field=models.CharField(default=None, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
