# Generated by Django 4.2.1 on 2023-06-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0005_alter_registeruser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='profile_picture',
            field=models.CharField(default='images/profile.jpg', max_length=100),
        ),
    ]
