# Generated by Django 4.2.1 on 2023-06-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0006_registeruser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='profile_picture',
            field=models.ImageField(upload_to='user/profiles'),
        ),
    ]
