# Generated by Django 4.2.1 on 2023-06-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0009_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='profile_picture',
            field=models.ImageField(default='profile.png', upload_to='user/profiles'),
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
